[[snippets]]
name = "d"
trigger = "d"
snippet = "docker"

[[snippets]]
name = "docker c"
trigger = "c"
snippet = "compose"
global = true
context = '^docker\s+\S+$'

[[snippets]]
name = "docker pl"
trigger = "pl"
snippet = "pull"
global = true
context = '^docker\s+\S+$'

[[snippets]]
name = "docker run"
trigger-pattern = "^r(?<rm>rm)?(?<it>i)?$"
snippet = "run${rm+ --rm}${it+ -it}"
global = true
evaluate = true
context = '^docker\s+\S+$'

[[snippets]]
name = "docker clean"
trigger = "clean"
snippet = "container prune -f"
global = true
context = '^docker\s+\S+$'

[[snippets]]
name = "docker cleani"
trigger = "cleani"
snippet = "image prune -f"
global = true
context = '^docker\s+\S+$'
